on: push
name: Slack Notification Demo
    
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
       curl -X POST --data-urlencode "payload={\"channel\": \"#deploy_status_nav\", \"username\": \"webhookbot\", \"text\": \"The UAT deployment is successful\", \"icon_emoji\": \":khanda:\"}" https://hooks.slack.com/services/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
